sub init()
    m.pokemonPoster = m.top.findNode("poster")
    m.pokemonLabel = m.top.findNode("pokemonLabel")
    m.top.findNode("focusPoster").blendColor = "#A0724A"
end sub

sub onItemContentChanged()
    pokemonContent = m.top.itemContent
    setPokemonItemFIelds(pokemonContent)
end sub

sub setPokemonItemFields(pokemonContent as object)
    m.pokemonPoster.uri = pokemonContent.url
    m.pokemonLabel.text = pokemonContent.title
end sub
